aider: feat: Add team filter to standup command

diff --git a/bin/linear b/bin/linear
--- a/bin/linear
+++ b/bin/linear
@@ -89,14 +89,24 @@ function standup() {
     fi
 
     date=${1:-$(date +%Y-%m-%d)}
+    
+    # Get the current team ID
+    dir=$(basename $(git rev-parse --show-toplevel))
+    teamId=$(echo $dir | ggrep -oP '^[a-zA-Z]{2,5}' | awk '{print toupper($0)}')
+
+    if [ -z "$teamId" ]; then
+        echo "Could not determine team id from directory name."
+        exit 1
+    fi
 
     query='
-    query($date: DateTimeOrDuration!) {
+    query($date: DateTimeOrDuration!, $teamId: String!) {
       issues(
         filter: {
           and: [
             { assignee: { isMe: { eq: true } } },
-            { updatedAt: { gte: $date } }
+            { updatedAt: { gte: $date } },
+            { team: { key: { eq: $teamId } } }
           ]
         }
       ) {
@@ -110,7 +120,7 @@ function standup() {
       }
     }'
 
-    variables=$(jo date="$date")
+    variables=$(jo date="$date" teamId="$teamId")
     data=$(jo query="$query" variables="$variables")
 
     response=$(curl -s -X POST \
