aider: feat: add 'view' command to print issue title and body in markdown format

diff --git a/bin/linear b/bin/linear
--- a/bin/linear
+++ b/bin/linear
@@ -83,7 +83,37 @@ function issue_title() {
 }
 
 function view() {
-    # TODO
+    issueId=$(id)
+
+    if [ -z "$LINEAR_API_KEY" ]; then
+        echo "LINEAR_API_KEY environment variable is not set."
+        exit 1
+    fi
+
+    if [ "$issueId" ]; then
+        query='query($id: String!) { issue(id: $id) { title, description } }'
+        variables=$(jo id="$issueId")
+        data=$(jo query="$query" variables="$variables")
+
+        response=$(curl -s -X POST \
+            -H "Content-Type: application/json" \
+            -H "Authorization: $LINEAR_API_KEY" \
+            --data "$data" \
+            https://api.linear.app/graphql)
+
+        title=$(echo $response | jq -r '.data.issue.title')
+        description=$(echo $response | jq -r '.data.issue.description')
+
+        if [ "$title" != "null" ] && [ "$description" != "null" ]; then
+            echo -e "# $title\n$(printf '=%.0s' $(seq 1 ${#title}))\n\n$description"
+        else
+            echo "Failed to fetch issue details. Make sure the issue ID is correct and you have the necessary permissions."
+            exit 1
+        fi
+    else
+        echo "The current branch does not contain a valid linear issue id."
+        exit 1
+    fi
 }
 
 CMD=${1:-""}
@@ -101,6 +131,7 @@ case $CMD in
         issue_title
         ;;
     view)
+        view
         view
         ;;
     *)
